server:
  port: 8080
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        max-idle: 10
        max-wait: 3000
        min-idle: 0
    timeout: 3000
